/**
 * 201 Holy Names of Prophet Muḥammad ﷺ
 * ======================================
 * From the sacred text Dalāʾilu l-Khayrāt of Imam Muḥammad al-Jazūlī
 * 
 * 🌙 Authorized Blessing:
 * Cherno Moussa Yero Sy — Spiritual Master of the Tijaniyya Order
 * 
 * Practice: 7-Day Rizq Abundance Challenge
 * - Recite Yā Jāmiʿu 180 times
 * - Recite all 201 Holy Names with Ṣalla-llāhu ʿalayhi wa sallam after each
 * - Morning and evening for 7 consecutive days
 */

export interface PropheticName {
  number: number;
  arabic: string;
  transliteration: string;
  meaning: string;
}

/** The 201 Holy Names of Prophet Muḥammad ﷺ */
export const PROPHETIC_NAMES_201: PropheticName[] = [
  { number: 1, arabic: 'مُحَمَّد', transliteration: 'Muḥammad', meaning: 'The Praised One' },
  { number: 2, arabic: 'أَحْمَد', transliteration: 'Aḥmad', meaning: 'The Most Praised' },
  { number: 3, arabic: 'حَامِد', transliteration: 'Ḥāmid', meaning: 'The Praiser' },
  { number: 4, arabic: 'مَحْمُود', transliteration: 'Maḥmūd', meaning: 'The Commended' },
  { number: 5, arabic: 'أَحِيد', transliteration: 'Aḥīd', meaning: 'The Unique' },
  { number: 6, arabic: 'وَاحِد', transliteration: 'Wāḥid', meaning: 'The One' },
  { number: 7, arabic: 'مَاحٍ', transliteration: 'Māḥin', meaning: 'The Eraser (of idolatry)' },
  { number: 8, arabic: 'حَاشِر', transliteration: 'Ḥāshirun', meaning: 'The Gatherer' },
  { number: 9, arabic: 'عَاقِب', transliteration: 'ʿĀqibun', meaning: 'The Last' },
  { number: 10, arabic: 'طَهَ', transliteration: 'Ṭāhā', meaning: 'O Pure One' },
  { number: 11, arabic: 'يَاسِين', transliteration: 'Yāsīn', meaning: 'O Mighty One' },
  { number: 12, arabic: 'طَاهِر', transliteration: 'Ṭāhirun', meaning: 'The Pure' },
  { number: 13, arabic: 'مُطَّهَر', transliteration: 'Muṭṭāharun', meaning: 'The Purified' },
  { number: 14, arabic: 'طَيِّب', transliteration: 'Ṭayyibun', meaning: 'The Good' },
  { number: 15, arabic: 'سَيِّد', transliteration: 'Sayyidun', meaning: 'The Master' },
  { number: 16, arabic: 'رَسُول', transliteration: 'Rasūlun', meaning: 'The Messenger' },
  { number: 17, arabic: 'نَبِيّ', transliteration: 'Nabīyyun', meaning: 'The Prophet' },
  { number: 18, arabic: 'رَسُولُ الرَّحْمَة', transliteration: 'Rasūlu r-raḥmati', meaning: 'The Messenger of Mercy' },
  { number: 19, arabic: 'قَيِّم', transliteration: 'Qayyimun', meaning: 'The Overseer' },
  { number: 20, arabic: 'جَامِع', transliteration: 'Jāmiʿun', meaning: 'The Gatherer' },
  { number: 21, arabic: 'مُقْتَفِ', transliteration: 'Muqtafin', meaning: 'The Follower' },
  { number: 22, arabic: 'مُقَفِّي', transliteration: 'Muqaffī', meaning: 'The Completing' },
  { number: 23, arabic: 'رَسُولُ الْمَلَاحِم', transliteration: 'Rasūlu l-malāḥimi', meaning: 'The Messenger of Battles' },
  { number: 24, arabic: 'رَسُولُ الرَّاحَة', transliteration: 'Rasūlu r-rāḥatun', meaning: 'The Messenger of Comfort' },
  { number: 25, arabic: 'كَامِل', transliteration: 'Kāmilun', meaning: 'The Perfect' },
  { number: 26, arabic: 'إِكْلِيل', transliteration: 'Iklīlun', meaning: 'The Crown' },
  { number: 27, arabic: 'مُدَثِّر', transliteration: 'Mudaththirun', meaning: 'The Cloaked One' },
  { number: 28, arabic: 'مُزَمِّل', transliteration: 'Muzammilun', meaning: 'The Wrapped One' },
  { number: 29, arabic: 'عَبْدُ الله', transliteration: 'ʿAbdullāhi', meaning: 'The Servant of Allah' },
  { number: 30, arabic: 'حَبِيبُ الله', transliteration: 'Ḥabībillāhi', meaning: 'The Beloved of Allah' },
  { number: 31, arabic: 'صَفِيُّ الله', transliteration: 'Ṣafiyullāhi', meaning: 'The Chosen of Allah' },
  { number: 32, arabic: 'نَجِيُّ الله', transliteration: 'Najiyyullāhi', meaning: 'The Confidant of Allah' },
  { number: 33, arabic: 'كَلِيمُ الله', transliteration: 'Kalīmullāhi', meaning: 'The Speaker with Allah' },
  { number: 34, arabic: 'خَاتَمُ الْأَنْبِيَاء', transliteration: 'Khātimu l-anbiyāʾi', meaning: 'Seal of the Prophets' },
  { number: 35, arabic: 'خَاتَمُ الرُّسُل', transliteration: 'Khātimu r-rusuli', meaning: 'Seal of the Messengers' },
  { number: 36, arabic: 'مُحْيِ', transliteration: 'Muḥyī', meaning: 'The Reviver' },
  { number: 37, arabic: 'مُنْجِ', transliteration: 'Munjin', meaning: 'The Rescuer' },
  { number: 38, arabic: 'مُذَكِّر', transliteration: 'Mudhakkirun', meaning: 'The Reminder' },
  { number: 39, arabic: 'نَاصِر', transliteration: 'Nāṣirun', meaning: 'The Helper' },
  { number: 40, arabic: 'مَنْصُور', transliteration: 'Manṣūrun', meaning: 'The Victorious' },
  { number: 41, arabic: 'نَبِيُّ الرَّحْمَة', transliteration: 'Nabīyyu r-raḥmati', meaning: 'The Prophet of Mercy' },
  { number: 42, arabic: 'نَبِيُّ التَّوْبَة', transliteration: 'Nabīyyu t-tawbati', meaning: 'The Prophet of Repentance' },
  { number: 43, arabic: 'حَرِيصٌ عَلَيْكُم', transliteration: 'Ḥarīsun ʿalaykum', meaning: 'The Watchful Over You' },
  { number: 44, arabic: 'مَعْلُوم', transliteration: 'Maʿlūmun', meaning: 'The Known One' },
  { number: 45, arabic: 'شَهِير', transliteration: 'Shahīrun', meaning: 'The Famous' },
  { number: 46, arabic: 'شَاهِد', transliteration: 'Shāhidun', meaning: 'The Witnesser' },
  { number: 47, arabic: 'شَهِيد', transliteration: 'Shahīdun', meaning: 'The Witness' },
  { number: 48, arabic: 'مَشْهُود', transliteration: 'Mashhūdun', meaning: 'The Attested' },
  { number: 49, arabic: 'بَشِير', transliteration: 'Bashīrun', meaning: 'The Glad-Tidings' },
  { number: 50, arabic: 'مُبَشِّر', transliteration: 'Mubashshirun', meaning: 'The Spreader of Good News' },
  { number: 51, arabic: 'نَذِير', transliteration: 'Nadhīrun', meaning: 'The Warner' },
  { number: 52, arabic: 'مُنْذِر', transliteration: 'Mundhirun', meaning: 'The Admonisher' },
  { number: 53, arabic: 'نُور', transliteration: 'Nūrun', meaning: 'The Light' },
  { number: 54, arabic: 'سِرَاج', transliteration: 'Sirājun', meaning: 'The Lamp' },
  { number: 55, arabic: 'مِصْبَاح', transliteration: 'Misbāḥun', meaning: 'The Lantern' },
  { number: 56, arabic: 'هُدًى', transliteration: 'Hudan', meaning: 'The Guidance' },
  { number: 57, arabic: 'مَهْدِيّ', transliteration: 'Mahdīyyun', meaning: 'The Rightly Guided' },
  { number: 58, arabic: 'مُنِير', transliteration: 'Munīrun', meaning: 'The Illumined One' },
  { number: 59, arabic: 'دَاعٍ', transliteration: 'Dāʿin', meaning: 'The Caller' },
  { number: 60, arabic: 'مَدْعُوّ', transliteration: 'Madʿūwwun', meaning: 'The Called One' },
  { number: 61, arabic: 'مُجِيب', transliteration: 'Mujībun', meaning: 'The Responsive' },
  { number: 62, arabic: 'مُجَاب', transliteration: 'Mujābun', meaning: 'The One Responded To' },
  { number: 63, arabic: 'حَفِيّ', transliteration: 'Ḥafiyyu', meaning: 'The Gentle' },
  { number: 64, arabic: 'عَفُوّ', transliteration: 'ʿAfūwwun', meaning: 'The Overlooker of Sins' },
  { number: 65, arabic: 'وَلِيّ', transliteration: 'Walīyyu', meaning: 'The Friend' },
  { number: 66, arabic: 'حَقّ', transliteration: 'Ḥaqqu', meaning: 'The Truth' },
  { number: 67, arabic: 'قَوِيّ', transliteration: 'Qawiyyu', meaning: 'The Powerful' },
  { number: 68, arabic: 'أَمِين', transliteration: 'Amīnun', meaning: 'The Trustworthy' },
  { number: 69, arabic: 'مَأْمُون', transliteration: 'Māʾmūnun', meaning: 'The Trusted' },
  { number: 70, arabic: 'كَرِيم', transliteration: 'Karīmun', meaning: 'The Generous' },
  { number: 71, arabic: 'مُكَرَّم', transliteration: 'Mukarramun', meaning: 'The Honored' },
  { number: 72, arabic: 'مَكِين', transliteration: 'Makīnun', meaning: 'The Firm' },
  { number: 73, arabic: 'مَتِين', transliteration: 'Matīnun', meaning: 'The Steadfast' },
  { number: 74, arabic: 'مُبِين', transliteration: 'Mubīnun', meaning: 'The Evident' },
  { number: 75, arabic: 'مُؤَمَّل', transliteration: 'Muʾammilun', meaning: 'The One Hoped For' },
  { number: 76, arabic: 'وَصُول', transliteration: 'Waṣūlun', meaning: 'The Connection' },
  { number: 77, arabic: 'ذُو قُوَّة', transliteration: 'Dhū-quwwatin', meaning: 'Possessor of Power' },
  { number: 78, arabic: 'ذُو حُرْمَة', transliteration: 'Dhū-ḥurmatin', meaning: 'Possessor of Honor' },
  { number: 79, arabic: 'ذُو مَكَانَة', transliteration: 'Dhū-makānatin', meaning: 'Possessor of Firmness' },
  { number: 80, arabic: 'ذُو عِزّ', transliteration: 'Dhū-ʿizzin', meaning: 'Possessor of Might' },
  { number: 81, arabic: 'ذُو فَضْل', transliteration: 'Dhū-faḍlin', meaning: 'Possessor of Grace' },
  { number: 82, arabic: 'مُطَاع', transliteration: 'Mutāʿun', meaning: 'The One Obeyed' },
  { number: 83, arabic: 'مُطِيع', transliteration: 'Muṭīʿun', meaning: 'The Obedient' },
  { number: 84, arabic: 'قَدَمُ صِدْق', transliteration: 'Qadamu ṣidqin', meaning: 'The Firm Foothold' },
  { number: 85, arabic: 'رَحْمَة', transliteration: 'Raḥmatun', meaning: 'Mercy' },
  { number: 86, arabic: 'بُشْرَى', transliteration: 'Bushrā', meaning: 'The Good News' },
  { number: 87, arabic: 'غَوْث', transliteration: 'Ghawthun', meaning: 'The Redeemer' },
  { number: 88, arabic: 'غَيْث', transliteration: 'Ghaythun', meaning: 'The Rain' },
  { number: 89, arabic: 'غِيَاث', transliteration: 'Ghiyāthun', meaning: 'The Rescuer' },
  { number: 90, arabic: 'نِعْمَةُ الله', transliteration: 'Niʿmatullāhi', meaning: 'The Favor of Allah' },
  { number: 91, arabic: 'هَدِيَّةُ الله', transliteration: 'Hadīyyatullāhi', meaning: 'The Gift of Allah' },
  { number: 92, arabic: 'عُرْوَةٌ وُثْقَى', transliteration: 'ʿUrwatun wuthqā', meaning: 'The Trusty Handhold' },
  { number: 93, arabic: 'صِرَاطُ الله', transliteration: 'Sirāṭullāhi', meaning: 'The Path of Allah' },
  { number: 94, arabic: 'صِرَاطٌ مُسْتَقِيم', transliteration: 'Sirāṭun mustaqīmun', meaning: 'The Straight Path' },
  { number: 95, arabic: 'ذِكْرُ الله', transliteration: 'Dhikrullāhi', meaning: 'The Remembrance of Allah' },
  { number: 96, arabic: 'سَيْفُ الله', transliteration: 'Sayfullāhi', meaning: 'The Sword of Allah' },
  { number: 97, arabic: 'حِزْبُ الله', transliteration: 'Ḥizbullāhi', meaning: 'The Party of Allah' },
  { number: 98, arabic: 'النَّجْمُ الثَّاقِب', transliteration: 'an-Najmu th-thāqibu', meaning: 'The Piercing Star' },
  { number: 99, arabic: 'مُصْطَفَى', transliteration: 'Muṣṭafā', meaning: 'The Chosen One' },
  { number: 100, arabic: 'مُجْتَبَى', transliteration: 'Mujtabā', meaning: 'The Singled-Out' },
  { number: 101, arabic: 'مُنْتَقَى', transliteration: 'Muntaqā', meaning: 'The Selected One' },
  { number: 102, arabic: 'أُمِّيّ', transliteration: 'Ummīyyun', meaning: 'The Unlettered' },
  { number: 103, arabic: 'مُخْتَار', transliteration: 'Mukhtārun', meaning: 'The Chosen' },
  { number: 104, arabic: 'أَجِير', transliteration: 'Ajīrun', meaning: 'Allah\'s Worker' },
  { number: 105, arabic: 'جَبَّار', transliteration: 'Jabbārun', meaning: 'The Compelling One' },
  { number: 106, arabic: 'أَبُو الْقَاسِم', transliteration: 'Abū l-Qāsimi', meaning: 'Father of Qāsim' },
  { number: 107, arabic: 'أَبُو الطَّاهِر', transliteration: 'Abū ṭ-Ṭāhiru', meaning: 'Father of Ṭāhir' },
  { number: 108, arabic: 'أَبُو الطَّيِّب', transliteration: 'Abū ṭ-Ṭayyib', meaning: 'Father of Ṭayyib' },
  { number: 109, arabic: 'أَبُو إِبْرَاهِيم', transliteration: 'Abū Ibrāhīma', meaning: 'Father of Ibrāhīm' },
  { number: 110, arabic: 'مُشَفَّع', transliteration: 'Mushaffaʿun', meaning: 'Whose Intercession is Accepted' },
  { number: 111, arabic: 'شَفِيع', transliteration: 'Shāfiʿun', meaning: 'The Interceder' },
  { number: 112, arabic: 'صَالِح', transliteration: 'Ṣāliḥun', meaning: 'The Righteous' },
  { number: 113, arabic: 'مُصْلِح', transliteration: 'Muṣliḥun', meaning: 'The Conciliator' },
  { number: 114, arabic: 'مُهَيْمِن', transliteration: 'Muhayminun', meaning: 'The Guardian' },
  { number: 115, arabic: 'صَادِق', transliteration: 'Ṣādiqun', meaning: 'The Truthful' },
  { number: 116, arabic: 'مُصَدِّق', transliteration: 'Muṣaddaqun', meaning: 'The Confirmer' },
  { number: 117, arabic: 'صِدْق', transliteration: 'Ṣidqun', meaning: 'Sincerity' },
  { number: 118, arabic: 'سَيِّدُ الْمُرْسَلِين', transliteration: 'Sayyidu l-mursalīna', meaning: 'Master of Messengers' },
  { number: 119, arabic: 'إِمَامُ الْمُتَّقِين', transliteration: 'Imāmu l-muttaqīna', meaning: 'Leader of the God-Fearing' },
  { number: 120, arabic: 'قَائِدُ الْغُرِّ الْمُحَجَّلِين', transliteration: 'Qāʾidu l-ghurri l-muḥajjalīna', meaning: 'Guide of the Bright Shining Ones' },
  { number: 121, arabic: 'خَلِيلُ الرَّحْمَن', transliteration: 'Khalīlu r-raḥmāni', meaning: 'Friend of the Merciful' },
  { number: 122, arabic: 'بَرّ', transliteration: 'Barrun', meaning: 'The Pious' },
  { number: 123, arabic: 'مَبَرّ', transliteration: 'Mabarrun', meaning: 'The Venerated' },
  { number: 124, arabic: 'وَجِيه', transliteration: 'Wajīhun', meaning: 'The Eminent' },
  { number: 125, arabic: 'نَصِيح', transliteration: 'Naṣīḥun', meaning: 'The Adviser' },
  { number: 126, arabic: 'نَاصِح', transliteration: 'Nāṣiḥun', meaning: 'The Counselor' },
  { number: 127, arabic: 'وَكِيل', transliteration: 'Wakīlun', meaning: 'The Advocate' },
  { number: 128, arabic: 'مُتَوَكِّل', transliteration: 'Mutawakkilun', meaning: 'The Reliant on Allah' },
  { number: 129, arabic: 'كَفِيل', transliteration: 'Kafīlun', meaning: 'The Guarantor' },
  { number: 130, arabic: 'شَفِيق', transliteration: 'Shafīqun', meaning: 'The Tender' },
  { number: 131, arabic: 'مُقِيمُ السُّنَّة', transliteration: 'Muqīmu s-sunnati', meaning: 'Establisher of the Way' },
  { number: 132, arabic: 'مُقَدَّس', transliteration: 'Muqaddasu', meaning: 'The Sacred' },
  { number: 133, arabic: 'رُوحُ الْقُدُس', transliteration: 'Rūḥu l-qudusi', meaning: 'The Holy Spirit' },
  { number: 134, arabic: 'رُوحُ الْحَقّ', transliteration: 'Rūḥu l-ḥaqqi', meaning: 'The Spirit of Truth' },
  { number: 135, arabic: 'رُوحُ الْقِسْط', transliteration: 'Rūḥu l-qisṭi', meaning: 'The Spirit of Justice' },
  { number: 136, arabic: 'كَافٍ', transliteration: 'Kāfin', meaning: 'The Qualified' },
  { number: 137, arabic: 'مُكْتَفِ', transliteration: 'Muktafin', meaning: 'The Broad-Shouldered One' },
  { number: 138, arabic: 'بَالِغ', transliteration: 'Bālighun', meaning: 'The Proclaimer' },
  { number: 139, arabic: 'مُبَلِّغ', transliteration: 'Muballighun', meaning: 'The Informer' },
  { number: 140, arabic: 'شَافٍ', transliteration: 'Shāfin', meaning: 'The Healing' },
  { number: 141, arabic: 'وَاصِل', transliteration: 'Wāṣilun', meaning: 'The Inseparable Friend' },
  { number: 142, arabic: 'مَوْصُول', transliteration: 'Mawṣūlun', meaning: 'The One Bound to Allah' },
  { number: 143, arabic: 'سَابِق', transliteration: 'Sābiqun', meaning: 'The Foremost' },
  { number: 144, arabic: 'سَائِق', transliteration: 'Sāʾiqun', meaning: 'The Driver' },
  { number: 145, arabic: 'هَادٍ', transliteration: 'Hādin', meaning: 'The Guide' },
  { number: 146, arabic: 'مُهْتَدٍ', transliteration: 'Muhtadin', meaning: 'The Guided' },
  { number: 147, arabic: 'مُقَدَّم', transliteration: 'Muqaddamun', meaning: 'The Overseer' },
  { number: 148, arabic: 'عَزِيز', transliteration: 'ʿAzīzun', meaning: 'The Mighty' },
  { number: 149, arabic: 'فَاضِل', transliteration: 'Fāḍilun', meaning: 'The Outstanding' },
  { number: 150, arabic: 'مُفَضَّل', transliteration: 'Mufaḍḍalun', meaning: 'The Favoured' },
  { number: 151, arabic: 'فَاتِح', transliteration: 'Fātiḥun', meaning: 'The Opener' },
  { number: 152, arabic: 'مِفْتَاح', transliteration: 'Miftāḥun', meaning: 'The Key' },
  { number: 153, arabic: 'مِفْتَاحُ الرَّحْمَة', transliteration: 'Miftāḥu r-raḥmah', meaning: 'The Key to Mercy' },
  { number: 154, arabic: 'مِفْتَاحُ الْجَنَّة', transliteration: 'Miftāḥu l-jannah', meaning: 'The Key to the Garden' },
  { number: 155, arabic: 'عَلَمُ الْإِيمَان', transliteration: 'ʿAlamu l-īmāni', meaning: 'Teacher of Faith' },
  { number: 156, arabic: 'عَلَمُ الْيَقِين', transliteration: 'ʿAlamu l-yaqīni', meaning: 'Teacher of Certainty' },
  { number: 157, arabic: 'دَلِيلُ الْخَيْرَات', transliteration: 'Dalīlu l-khayrāti', meaning: 'Guide to Good Things' },
  { number: 158, arabic: 'مُصَحِّحُ الْحَسَنَات', transliteration: 'Muṣaḥḥihu l-ḥasanāti', meaning: 'Verifier of Good Deeds' },
  { number: 159, arabic: 'مُقِيلُ الْعَثَرَات', transliteration: 'Muqīlu l-ʿatharāti', meaning: 'Remover of Obstacles' },
  { number: 160, arabic: 'صَفُوحٌ عَنِ الزَّلَّات', transliteration: 'Ṣafūḥun ʿani z-zallāti', meaning: 'Pardoner of Sins' },
  { number: 161, arabic: 'صَاحِبُ الشَّفَاعَة', transliteration: 'Ṣāhibu l-shafāʿati', meaning: 'Possessor of Intercession' },
  { number: 162, arabic: 'صَاحِبُ الْمَقَام', transliteration: 'Ṣāhibu l-maqāmi', meaning: 'Possessor of the Honored Station' },
  { number: 163, arabic: 'صَاحِبُ الْقَدَم', transliteration: 'Ṣāhibu l-qadami', meaning: 'Owner of the Footprint' },
  { number: 164, arabic: 'مَخْصُوصٌ بِالْعِزّ', transliteration: 'Makhṣūṣun bi l-ʿizzi', meaning: 'Distinguished with Might' },
  { number: 165, arabic: 'مَخْصُوصٌ بِالْمَجْد', transliteration: 'Makhṣūṣun bi l-majdi', meaning: 'Distinguished with Glory' },
  { number: 166, arabic: 'مَخْصُوصٌ بِالشَّرَف', transliteration: 'Makhṣūṣun bi sh-sharafi', meaning: 'Distinguished with Nobility' },
  { number: 167, arabic: 'صَاحِبُ الْوَسِيلَة', transliteration: 'Ṣāhibu l-wasīlati', meaning: 'Possessor of Closest Access' },
  { number: 168, arabic: 'صَاحِبُ السَّيْف', transliteration: 'Ṣāhibu s-sayfi', meaning: 'Owner of the Sword' },
  { number: 169, arabic: 'صَاحِبُ الْفَضِيلَة', transliteration: 'Ṣāhibu l-faḍīlata', meaning: 'Possessor of Pre-eminence' },
  { number: 170, arabic: 'صَاحِبُ الْإِزَار', transliteration: 'Ṣāhibu l-izāri', meaning: 'Owner of the Waist-Wrap' },
  { number: 171, arabic: 'صَاحِبُ الْحُجَّة', transliteration: 'Ṣāhibu l-ḥujjati', meaning: 'Possessor of Proof' },
  { number: 172, arabic: 'صَاحِبُ السُّلْطَان', transliteration: 'Ṣāhibu s-sulṭāni', meaning: 'Possessor of Authority' },
  { number: 173, arabic: 'صَاحِبُ الرِّدَاء', transliteration: 'Ṣāhibu r-ridāʾi', meaning: 'Owner of the Robe' },
  { number: 174, arabic: 'صَاحِبُ الدَّرَجَةِ الرَّفِيعَة', transliteration: 'Ṣāhibu d-darajati r-rafīʿati', meaning: 'Possessor of the Lofty Rank' },
  { number: 175, arabic: 'صَاحِبُ التَّاج', transliteration: 'Ṣāhibu t-tāji', meaning: 'Possessor of the Crown' },
  { number: 176, arabic: 'صَاحِبُ الْمِغْفَر', transliteration: 'Ṣāhibu l-mighfari', meaning: 'Possessor of Forgiveness' },
  { number: 177, arabic: 'صَاحِبُ اللِّوَاء', transliteration: 'Ṣāhibu l-liwāʾi', meaning: 'Possessor of the Flag' },
  { number: 178, arabic: 'صَاحِبُ الْمِعْرَاج', transliteration: 'Ṣāhibu l-miʿrāji', meaning: 'Master of the Night Journey' },
  { number: 179, arabic: 'صَاحِبُ الْقَضِيب', transliteration: 'Ṣāhibu l-qaḍībi', meaning: 'Possessor of the Staff' },
  { number: 180, arabic: 'صَاحِبُ الْبُرَاق', transliteration: 'Ṣāhibu l-burāqi', meaning: 'Owner of the Burāq' },
  { number: 181, arabic: 'صَاحِبُ الْخَاتَم', transliteration: 'Ṣāhibu l-khātami', meaning: 'Owner of the Ring' },
  { number: 182, arabic: 'صَاحِبُ الْعَلَامَة', transliteration: 'Ṣāhibu l-ʿalāmati', meaning: 'Owner of the Sign' },
  { number: 183, arabic: 'صَاحِبُ الْبُرْهَان', transliteration: 'Ṣāhibu l-burhānu', meaning: 'Possessor of the Evidence' },
  { number: 184, arabic: 'صَاحِبُ الْبَيَان', transliteration: 'Ṣāhibu l-bayāni', meaning: 'Possessor of Evident Proof' },
  { number: 185, arabic: 'فَصِيحُ اللِّسَان', transliteration: 'Faṣīḥu l-lisāni', meaning: 'The Good Communicator' },
  { number: 186, arabic: 'مُطَّهَرُ الْجَنَان', transliteration: 'Muṭṭaharu l-janani', meaning: 'Purifier of the Souls' },
  { number: 187, arabic: 'رَؤُوف', transliteration: 'Raʾūfun', meaning: 'The Kind' },
  { number: 188, arabic: 'رَحِيم', transliteration: 'Raḥīmun', meaning: 'The Mercy Giving' },
  { number: 189, arabic: 'أُذُنُ خَيْر', transliteration: 'Udhunu khayrin', meaning: 'The Good Listener' },
  { number: 190, arabic: 'صَحِيحُ الْإِسْلَام', transliteration: 'Ṣaḥīḥu l-Islāmi', meaning: 'The One with Perfect Islam' },
  { number: 191, arabic: 'سَيِّدُ الْكَوْنَيْن', transliteration: 'Sayyidu l-kawnayn', meaning: 'Master of the Two Universes' },
  { number: 192, arabic: 'عَيْنُ النَّعِيم', transliteration: 'ʿAynu n-naʿīmi', meaning: 'The Spring of Bliss' },
  { number: 193, arabic: 'عَيْنُ الْغُرّ', transliteration: 'ʿAynu l-ghurri', meaning: 'The Spring of Beauty' },
  { number: 194, arabic: 'سَعْدُ الله', transliteration: 'Saʿdullāhi', meaning: 'The Joy of Allah' },
  { number: 195, arabic: 'سَعْدُ الْخَلْق', transliteration: 'Saʿdu l-khalqi', meaning: 'The Joy of the Creator' },
  { number: 196, arabic: 'خَطِيبُ الْأُمَم', transliteration: 'Khaṭību l-ʿumami', meaning: 'The Preacher to Nations' },
  { number: 197, arabic: 'عَلَمُ الْهُدَى', transliteration: 'ʿAlamu l-hudā', meaning: 'The Teacher of Guidance' },
  { number: 198, arabic: 'كَاشِفُ الْكُرَب', transliteration: 'Kāshifu l-kurabi', meaning: 'The Remover of Worries' },
  { number: 199, arabic: 'رَافِعُ الرُّتَب', transliteration: 'Rāfiʿu r-rutabi', meaning: 'The Raiser of Rank' },
  { number: 200, arabic: 'عِزُّ الْعَرَب', transliteration: 'ʿIzzu l-ʿArabi', meaning: 'The Might of the Arab' },
  { number: 201, arabic: 'صَاحِبُ الْفَرَج', transliteration: 'Ṣāhibu l-faraji', meaning: 'The Owner of Relief' },
];

/** Yā Jāmiʿu — The Gathering Name recited 180 times before the 201 Names */
export const YA_JAMIU = {
  arabic: 'يَا جَامِعُ',
  transliteration: 'Yā Jāmiʿu',
  meaning: 'O Gatherer, O Mighty One',
  count: 180,
};

/** Opening Duʿāʾ for Rizq */
export const RIZQ_DUA = {
  arabic: `اللَّهُمَّ إِنِّي أَسْأَلُكَ رِزْقًا وَاسِعًا مِنْ حَيْثُ لَا أَحْتَسِبُ
وَبَرَكَةً فِيهِ وَتَوْفِيقًا لِطَاعَتِكَ
آمِين آمِين آمِين`,
  transliteration: `Allāhumma inī asʾaluka rizqan wāsiʿan min ḥaythu lā aḥtasib,
wa barakatan fīhi, wa tawfīqan li-ṭāʿatika.
Amīn, Amīn, Amīn.`,
  meaning: 'O Allah, I ask You for abundant provision from sources I do not expect, blessing in it, and success in Your obedience. Amīn, Amīn, Amīn.',
};

/** Closing Duʿāʾ from Dalāʾilu l-Khayrāt */
export const CLOSING_DUA = {
  arabic: `اللَّهُمَّ يَا رَبِّ بِجَاهِ نَبِيِّكَ الْمُصْطَفَى وَرَسُولِكَ الْمُرْتَضَى
طَهِّرْ قُلُوبَنَا مِنْ كُلِّ وَصْفٍ يُبَاعِدُنَا عَنْ مُشَاهَدَتِكَ وَمَحَبَّتِكَ
وَأَمِتْنَا عَلَى السُّنَّةِ وَالْجَمَاعَةِ وَالشَّوْقِ إِلَى لِقَائِكَ
يَا ذَا الْجَلَالِ وَالْإِكْرَام`,
  transliteration: `Allāhumma yā rabbī bi-jāhi Nabīyyika l-Muṣṭafā wa Rasūlika l-Murtaḍā
ṭahhir qulūbanā min kulli waṣfin yubāʿidunā ʿan mushāhadatika wa maḥabbatika
wa amitnā ʿalā s-sunnati wa l-jamāʿati wa sh-shawqi ilā liqāʾika
yā Dhal-Jalāli wa l-Ikrām.`,
  meaning: 'O Allah, O Lord — by the honor of Your Chosen Prophet and Your Messenger with whom You are well pleased — purify our hearts from every trait that keeps us from beholding You and from Your Love. Cause us to depart this world following his way, his community, and longing to meet You — O Owner of Majesty and Nobility.',
};

/** Practice metadata */
export const RIZQ_PRACTICE_INFO = {
  title: '201 Holy Names of Prophet Muḥammad ﷺ',
  subtitle: 'Rizq Abundance Practice',
  tradition: 'Dalāʾilu l-Khayrāt · Imam Muḥammad al-Jazūlī',
  authorization: 'Cherno Moussa Yero Sy — Spiritual Master of the Tijaniyya Order',
  duration: 7, // days
  sessionsPerDay: 2, // morning + evening
  totalSessions: 14,
  estimatedTime: '25-35 minutes per session',
  description: 'For those seeking immense abundance, provision, and divine sustenance (Rizq), recite Yā Jāmiʿu 180 times followed by all 201 Holy Names with Ṣalla-llāhu ʿalayhi wa sallam after each name. Practice morning and evening for 7 consecutive days.',
  promise: 'Immeasurable changes in your rizq, abundance, and divine provision will manifest.',
};
